### ISSUE TITLE
No data returned from GCP KMS decryption function

### ISSUE THREAD

**Issue by mblackbourne** [googleapis/nodejs-kms#391]
When using the decryptSymmetric function there is no returning data. 

```js
const {KeyManagementServiceClient} = require('@google-cloud/kms');

// Instantiates a client
const client = new KeyManagementServiceClient();
const keyName = client.cryptoKeyPath(projectId, locationId, keyRingId, keyId);

async function decryptSymmetric(ciphertext) {
  console.log(ciphertext.toString('base64'));
  const [result] = await client.decrypt({
    name: keyName,
    ciphertext: ciphertext,
  });
  
  const plaintext = result.plaintext.toString('utf-8');

  console.log(`Plaintext: ${plaintext}`);
  return plaintext;
}
```

I am expecting a return plaintext that is in base64  and getting: 

```
Serving function...
Function: helloWorld
URL: http://localhost:3030/
CiQA4vWCb+DocwFpiThkYYyO48JyFKIJ5McAd/XT0t/9Rq4k258SIQA+ePV/vGbIerd0M5OFRgo+tFKtl1JJiwCHtvWlVdd1rw==

Plaintext:
Decrypt results: 
```

Docs I am following: https://cloud.google.com/kms/docs/encrypt-decrypt

**Comment by hhklik** [comment]
Eliminen la linea:
`const ciphertext = Buffer.from(get_ciphertext);`

En su lugar coloque
`let ciphertext = '<valor en base64>';`

sustituir `<valor en base64>` por la cadena base64 que genera **client.encrypt** 
**IMPORTANTE: sin decodificar el base64**


```const projectId = 'pos-chapin';
	const locationId = 'us-east1';
	const keyRingId = 'tcsecure';
	const keyId = 'tcsecureone';
	//const ciphertext = Buffer.from(get_ciphertext);
	let ciphertext = '<valor en base64>';

	// Imports the Cloud KMS library
	//const {KeyManagementServiceClient} = require('@google-cloud/kms');

	// Instantiates a client
	const client = new KeyManagementServiceClient();

	// Build the key name
	const keyName = client.cryptoKeyPath(projectId, locationId, keyRingId, keyId);

	async function decryptSymmetric() {
	  const [result] = await client.decrypt({
	    name: keyName,
	    ciphertext: ciphertext,
	  });

	  //const plaintext = result.plaintext.toString('utf8');
	  
	  const plaintext = result.plaintext;

	  console.log(\`Plaintext: ${plaintext}\`);
	  return plaintext;
	}
	
	return decryptSymmetric();```

**Comment by rhyeen** [comment]
For Typescript users, I got these two snippets to work.

For encryption:
```
const [response] = await client.encrypt({
      name: keyName,
      plaintext: Buffer.from(plaintext).toString('base64'), // e.g. decryptedStr from below snippet
});
const encryptedStr = Buffer.from(response.ciphertext || '').toString('base64');
```
For decryption:
```
const [response] = await client.decrypt({
  name: keyName,
  ciphertext: base64Ciphertext, // e.g. encryptedStr from above snippet
});
const decryptedStr = Buffer.from(response.plaintext || '').toString('utf8');
```

**Comment by bcoe** [comment]
@rhyeen am I following correctly that the samples are missing the `.toString('base64')` which made things work for you?

**Comment by rhyeen** [comment]
@bcoe somewhat.  The samples work (as in this [encryption sample](https://github.com/googleapis/nodejs-kms/blob/master/samples/encryptSymmetric.js#L51) and this [decryption sample](https://github.com/googleapis/nodejs-kms/blob/master/samples/decryptSymmetric.js#L49); but only in Javascript.  In Typescript, it's a compiler error because `ciphertext.toString('base64')` and `result.plaintext.toString('utf8')` are 1) not checking if `ciphertext`/`result.plaintext` are `undefined`, `string`, or `Uint8Array` and 2) for `string`, or `Uint8Array`, `.toString()` does not have any parameters.

Now, I don't know how it's working in Javascript given (1) and (2), but in Typescript, you essentially need to replace `ciphertext.toString('base64')` and `result.plaintext.toString('utf8')` with `Buffer.from(ciphertext || '').toString('base64');` and `Buffer.from(result.plaintext || '').toString('utf8');` respectively.

It should also be noted that both `.decrypt` and `.encrypt` expect `plaintext` and `ciphertext` respectively to be base 64 encoded and will hang indefinitely if not provided as such.

**Comment by bcoe** [comment]
@mblackbourne have you been able to get your application working? If so what changes did you need to make?

**Comment by mblackbourne** [comment]
@bcoe Never got my node version to work. Ended up just building it in python.

**Comment by sofisl** [comment]
@rhyeen, thanks for digging into this!

In attempting to reproduce the issue, I think the main issue is that the function expects `ciphertext` to be either a Buffer or a base-64 encoded string. There is also the issue compiling Typescript, since Typescript does not know what to expect back. However, we can coerce the type as follows in Typescript and Javascript (without the optional chaining):

`const plaintext = decryptResponse.plaintext?.toString();`

Our generator is limited as it must return the types that it accepts, however, this particular function will always just return a Buffer.

I will update documentation on this sample accordingly to create less confusion!
