### ISSUE TITLE
tests are leaking keyrings

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-kms#470]
Looking at the CI project, we appear to be leaking KeyRing objects.

**Comment by NimJay** [comment]
Since we have migrated the `samples` from this repository to [github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/main/kms](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/main/kms), I have moved this GitHub issue to https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/2852.
