### ISSUE TITLE
Significant overhead / delay decrypting on cloudfunctions at first

### ISSUE THREAD

**Issue by acoulton** [googleapis/nodejs-kms#99]
I'm trying to decrypt a simple & small (2.3kB) config file at runtime in a cloud function. The first time it runs in an environment (e.g. after deployment / sleeping) it overall takes more than 2 seconds to complete the config loading. This is a huge overhead compared to the ~ 275ms to call the API directly with the google-auth-library. I realise this can be mitigated by caching the result in globals etc, but 2+ seconds is still quite a long time even if only for the "cold start" requests.

#### Environment details

  - OS: Google CloudFunctions
  - Node.js version: 8
  - npm version: (cloud functions default)
  - `@google-cloud/kms` version: 0.2.0

#### Steps to reproduce

  1. Create an encrypted file, ensure cloud functions service account has permission to decrypt with the key
  2. Create a cloud function using this library and call it:
```
const kms = require('@google-cloud/kms');

async function decryptConfig(ciphertext, key_config) {
    const client = new kms.KeyManagementServiceClient();
    const key_path = client.cryptoKeyPath(key_config.project, key_config.location, key_config.keyring, key_config.key);
    const [result] = await client.decrypt({name: key_path, ciphertext: ciphertext});
    return result.plaintext;
}

async function promiseLoad(file, encoding) {
    return new Promise((resolve) => {
        fs.readFile(file, {encoding: encoding}, (err, data) => {
            if (err) throw err;
            resolve(data);
        })
    });
}

module.exports.kmstest = async (request, response) => {
    const ciphertext = await promiseLoad(path.resolve(__dirname, 'config/test.json.enc'), 'base64');
    const plaintext = await decryptConfig(
        ciphertext,
        {
            "project": "#your-project",
            "location": "global",
            "keyring": "#your-keyring",
            "key": "#your-key"
        }
    );
    response.send(plaintext);
}

```
  3. Create a cloud function that just reads it directly with `google-auth-client`:
```
const {auth} = require('google-auth-library');
async function decryptConfig(ciphertext, key_config) {
    const client = await auth.getClient({scopes: 'https://www.googleapis.com/auth/cloud-platform'});
    const url = `https://cloudkms.googleapis.com/v1/projects/${key_config.project}/locations/${key_config.location}/keyRings/${key_config.keyring}/cryptoKeys/${key_config.key}:decrypt`;
    const result = await client.request({url, method: 'POST', data: {ciphertext: ciphertext}});
    return Buffer.from(result.data.plaintext, 'base64').toString('utf8');
}

/** calling code as above */
```
4. Call both functions and observe that the raw HTTP request is significantly faster.

I did a bit of hacking and benchmarking and it looks like the biggest issue is the setup time to create an instance of the KeyManagementClient, which seems to be related to creating the gaxGrpc client. I was consistently (on cold start) getting timings like:

| benchmark point | time | elapsed_ms |
|------------------------|-------------------|------------------|
| start                     | 00:32:33:981 | ##                |
| ciphertext loaded | 00:32:33:989 | +8 |
| [assigned options (..._service_client.js:81)](https://github.com/googleapis/nodejs-kms/blob/master/src/v1/key_management_service_client.js#L81) | 00:32:33:990 | +1 |
| [created gaxGrpc (..._service_client.js:84)](https://github.com/googleapis/nodejs-kms/blob/master/src/v1/key_management_service_client.js#L84)         |00:32:35:083 | +1094 | 
| KMS client created (on return from constructor) | 00:32:35:387 | +304 |
| Key path calculated      | 00:32:35:389 | +2 |
| decrypted                | 00:32:36:116 | +727 |

**Comment by bcoe** [comment]
@acoulton thank you for the thorough benchmarks; sorry it's been quite some time since we followed up with you.

Since this ticket was opened, we've made a few changes:

1. we've switched to `grpc-js` from `grpc`, eliminating the need for a compiled dependency (it's my hunch that this might load a bit faster in cloud functions).
2. we've made some performance improvements, eliminating the loading of some unneeded protos.

Would you be able to run this same test with the up-to-date versions of this library?

**Comment by JustinBeckwith** [comment]
Looking at the source code above - I see one weird trick you can do to really speed this up.  It looks like you're creating a new `KeyManagementServiceClient` during each request.  Every time you do that, it goes through a bunch of allocations and network calls to acquire auth credentials.  Instead - can you move this line out of the function, and right below the require?

```js
const kms = require('@google-cloud/kms');
const client = new kms.KeyManagementServiceClient();

async function decryptConfig(ciphertext, key_config) {
    // do stuff
}
```

This will ensure that you only do all that stuff during cold start.  

Another thing you can generally do - reduce the number of dependencies in your package.json.  The number of files that need to be loaded will have a direct correlation to cold start times.

Finally - as @bcoe called out - we have done a lot of work here on load time since 0.2:
https://npmtrace.appspot.com/trend/@google-cloud/kms

![image](https://user-images.githubusercontent.com/534619/61247366-c4351900-a705-11e9-88d5-0c527f666e18.png)

We went from ~1300ms for load time in `0.2.0` to ~285ms for `1.3.0`.  For now - I am going to close this out.  Please do let us know if there's anything else we can do here!
